//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.17 at 09:00:09 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.org/TicketAgent.xsd")
package com.home.springws.autogen;
